/**
 * Anvl — In-process Telegram WebApp SDK mock.
 *
 * Implements a faithful subset of `window.Telegram.WebApp` so that bot/mini-app
 * code generated by Anvl can call the real API surface inside the preview.
 * In a real Telegram client the host app provides this object; outside Telegram
 * we provide the same shape so behaviour is identical end-to-end.
 *
 * Features supported (mock):
 *   - MainButton (text, color, show/hide, enable/disable, onClick, showProgress)
 *   - BackButton (show/hide, onClick)
 *   - HapticFeedback (impactOccurred, notificationOccurred, selectionChanged) via navigator.vibrate
 *   - CloudStorage (setItem/getItem/removeItem/getKeys) backed by localStorage
 *   - initData / initDataUnsafe (mock user)
 *   - themeParams + colorScheme
 *   - ready(), expand(), close(), sendData(), showAlert(), showConfirm(), showPopup()
 */

type EventHandler = (...args: unknown[]) => void;

export interface TelegramMainButton {
  text: string;
  color: string;
  textColor: string;
  isVisible: boolean;
  isActive: boolean;
  isProgressVisible: boolean;
  setText(text: string): TelegramMainButton;
  onClick(handler: EventHandler): TelegramMainButton;
  offClick(handler: EventHandler): TelegramMainButton;
  show(): TelegramMainButton;
  hide(): TelegramMainButton;
  enable(): TelegramMainButton;
  disable(): TelegramMainButton;
  showProgress(leaveActive?: boolean): TelegramMainButton;
  hideProgress(): TelegramMainButton;
  setParams(params: Partial<{
    text: string;
    color: string;
    text_color: string;
    is_active: boolean;
    is_visible: boolean;
  }>): TelegramMainButton;
}

export interface TelegramBackButton {
  isVisible: boolean;
  onClick(handler: EventHandler): TelegramBackButton;
  offClick(handler: EventHandler): TelegramBackButton;
  show(): TelegramBackButton;
  hide(): TelegramBackButton;
}

export interface TelegramHapticFeedback {
  impactOccurred(style: "light" | "medium" | "heavy" | "rigid" | "soft"): TelegramHapticFeedback;
  notificationOccurred(type: "error" | "success" | "warning"): TelegramHapticFeedback;
  selectionChanged(): TelegramHapticFeedback;
}

export interface TelegramCloudStorage {
  setItem(key: string, value: string, cb?: (err: Error | null, ok?: boolean) => void): void;
  getItem(key: string, cb: (err: Error | null, value?: string) => void): void;
  getItems(keys: string[], cb: (err: Error | null, values?: Record<string, string>) => void): void;
  removeItem(key: string, cb?: (err: Error | null, ok?: boolean) => void): void;
  removeItems(keys: string[], cb?: (err: Error | null, ok?: boolean) => void): void;
  getKeys(cb: (err: Error | null, keys?: string[]) => void): void;
}

export interface TelegramWebApp {
  initData: string;
  initDataUnsafe: {
    user?: { id: number; first_name: string; last_name?: string; username?: string; language_code?: string };
    auth_date?: number;
    hash?: string;
  };
  version: string;
  platform: string;
  colorScheme: "light" | "dark";
  themeParams: Record<string, string>;
  isExpanded: boolean;
  viewportHeight: number;
  viewportStableHeight: number;
  headerColor: string;
  backgroundColor: string;
  MainButton: TelegramMainButton;
  BackButton: TelegramBackButton;
  HapticFeedback: TelegramHapticFeedback;
  CloudStorage: TelegramCloudStorage;
  ready(): void;
  expand(): void;
  close(): void;
  sendData(data: string): void;
  switchInlineQuery(query: string, choose_chat_types?: string[]): void;
  openLink(url: string, options?: { try_instant_view?: boolean }): void;
  openTelegramLink(url: string): void;
  showAlert(message: string, cb?: () => void): void;
  showConfirm(message: string, cb?: (ok: boolean) => void): void;
  showPopup(
    params: { title?: string; message: string; buttons?: { id?: string; type?: string; text?: string }[] },
    cb?: (id: string) => void,
  ): void;
  onEvent(eventType: string, handler: EventHandler): void;
  offEvent(eventType: string, handler: EventHandler): void;
  setHeaderColor(color: string): void;
  setBackgroundColor(color: string): void;
}

interface MockState {
  mainButtonText: string;
  mainButtonColor: string;
  mainButtonTextColor: string;
  mainButtonVisible: boolean;
  mainButtonActive: boolean;
  mainButtonProgress: boolean;
  backButtonVisible: boolean;
  mainHandlers: Set<EventHandler>;
  backHandlers: Set<EventHandler>;
  events: Map<string, Set<EventHandler>>;
}

const CLOUD_PREFIX = "anvl.tg.cloud.";

export interface TmaMockOptions {
  /** Triggered any time visible button state changes — used to re-render the UI. */
  onChange?: () => void;
  /** Replace `window.alert` / `window.confirm` for the alert/confirm/popup helpers. */
  alert?: (msg: string) => Promise<void> | void;
  confirm?: (msg: string) => Promise<boolean> | boolean;
}

export interface TmaMockHandle {
  webApp: TelegramWebApp;
  state: MockState;
  triggerMainClick: () => void;
  triggerBackClick: () => void;
  reset: () => void;
}

function safeVibrate(ms: number | number[]) {
  if (typeof navigator === "undefined") return;
  const v = (navigator as Navigator & { vibrate?: (p: number | number[]) => boolean }).vibrate;
  try {
    v?.(ms);
  } catch {
    /* noop */
  }
}

export function createTelegramWebAppMock(opts: TmaMockOptions = {}): TmaMockHandle {
  const state: MockState = {
    mainButtonText: "CONTINUE",
    mainButtonColor: "#3390EC",
    mainButtonTextColor: "#FFFFFF",
    mainButtonVisible: false,
    mainButtonActive: true,
    mainButtonProgress: false,
    backButtonVisible: false,
    mainHandlers: new Set(),
    backHandlers: new Set(),
    events: new Map(),
  };

  const notify = () => opts.onChange?.();

  const MainButton: TelegramMainButton = {
    get text() { return state.mainButtonText; },
    get color() { return state.mainButtonColor; },
    get textColor() { return state.mainButtonTextColor; },
    get isVisible() { return state.mainButtonVisible; },
    get isActive() { return state.mainButtonActive; },
    get isProgressVisible() { return state.mainButtonProgress; },
    setText(text) { state.mainButtonText = text; notify(); return this; },
    onClick(h) { state.mainHandlers.add(h); return this; },
    offClick(h) { state.mainHandlers.delete(h); return this; },
    show() { state.mainButtonVisible = true; notify(); return this; },
    hide() { state.mainButtonVisible = false; notify(); return this; },
    enable() { state.mainButtonActive = true; notify(); return this; },
    disable() { state.mainButtonActive = false; notify(); return this; },
    showProgress() { state.mainButtonProgress = true; notify(); return this; },
    hideProgress() { state.mainButtonProgress = false; notify(); return this; },
    setParams(params) {
      if (params.text !== undefined) state.mainButtonText = params.text;
      if (params.color !== undefined) state.mainButtonColor = params.color;
      if (params.text_color !== undefined) state.mainButtonTextColor = params.text_color;
      if (params.is_active !== undefined) state.mainButtonActive = params.is_active;
      if (params.is_visible !== undefined) state.mainButtonVisible = params.is_visible;
      notify();
      return this;
    },
  };

  const BackButton: TelegramBackButton = {
    get isVisible() { return state.backButtonVisible; },
    onClick(h) { state.backHandlers.add(h); return this; },
    offClick(h) { state.backHandlers.delete(h); return this; },
    show() { state.backButtonVisible = true; notify(); return this; },
    hide() { state.backButtonVisible = false; notify(); return this; },
  };

  const HapticFeedback: TelegramHapticFeedback = {
    impactOccurred(style) {
      const map = { light: 8, medium: 14, heavy: 22, rigid: 18, soft: 10 } as const;
      safeVibrate(map[style] ?? 10);
      return this;
    },
    notificationOccurred(type) {
      const map = { success: [10, 40, 10], warning: [12, 60, 12], error: [20, 30, 20, 30, 20] } as const;
      safeVibrate(map[type] ?? 10);
      return this;
    },
    selectionChanged() { safeVibrate(4); return this; },
  };

  const cloudKey = (k: string) => `${CLOUD_PREFIX}${k}`;
  const cloudKeys = () => {
    if (typeof localStorage === "undefined") return [];
    const out: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const k = localStorage.key(i);
      if (k?.startsWith(CLOUD_PREFIX)) out.push(k.slice(CLOUD_PREFIX.length));
    }
    return out;
  };

  const CloudStorage: TelegramCloudStorage = {
    setItem(key, value, cb) {
      try { localStorage.setItem(cloudKey(key), value); cb?.(null, true); }
      catch (e) { cb?.(e as Error); }
    },
    getItem(key, cb) {
      try { cb(null, localStorage.getItem(cloudKey(key)) ?? ""); }
      catch (e) { cb(e as Error); }
    },
    getItems(keys, cb) {
      try {
        const out: Record<string, string> = {};
        for (const k of keys) out[k] = localStorage.getItem(cloudKey(k)) ?? "";
        cb(null, out);
      } catch (e) { cb(e as Error); }
    },
    removeItem(key, cb) {
      try { localStorage.removeItem(cloudKey(key)); cb?.(null, true); }
      catch (e) { cb?.(e as Error); }
    },
    removeItems(keys, cb) {
      try { for (const k of keys) localStorage.removeItem(cloudKey(k)); cb?.(null, true); }
      catch (e) { cb?.(e as Error); }
    },
    getKeys(cb) { try { cb(null, cloudKeys()); } catch (e) { cb(e as Error); } },
  };

  const fireEvent = (type: string, ...args: unknown[]) => {
    state.events.get(type)?.forEach((h) => { try { h(...args); } catch { /* noop */ } });
  };

  const webApp: TelegramWebApp = {
    initData: "",
    initDataUnsafe: {
      user: { id: 99000099, first_name: "Sasha", username: "sasha", language_code: "ru" },
      auth_date: Math.floor(Date.now() / 1000),
      hash: "anvl_mock",
    },
    version: "7.0",
    platform: "anvl-preview",
    colorScheme: "dark",
    themeParams: {
      bg_color: "#17212b",
      text_color: "#f5f5f5",
      hint_color: "#7d8b99",
      link_color: "#6ab2f2",
      button_color: "#3390ec",
      button_text_color: "#ffffff",
      secondary_bg_color: "#232e3c",
    },
    isExpanded: true,
    viewportHeight: 520,
    viewportStableHeight: 520,
    headerColor: "#17212b",
    backgroundColor: "#17212b",
    MainButton,
    BackButton,
    HapticFeedback,
    CloudStorage,
    ready() { fireEvent("viewportChanged", { isStateStable: true }); },
    expand() { this.isExpanded = true; fireEvent("viewportChanged", { isStateStable: true }); },
    close() { fireEvent("close"); },
    sendData(data) { fireEvent("sendData", data); console.info("[TMA mock] sendData:", data); },
    switchInlineQuery(q) { console.info("[TMA mock] switchInlineQuery:", q); },
    openLink(url) { try { window.open(url, "_blank", "noopener,noreferrer"); } catch { /* noop */ } },
    openTelegramLink(url) { try { window.open(url, "_blank", "noopener,noreferrer"); } catch { /* noop */ } },
    async showAlert(message, cb) {
      if (opts.alert) { await opts.alert(message); } else { window.alert(message); }
      cb?.();
    },
    async showConfirm(message, cb) {
      const ok = opts.confirm ? await opts.confirm(message) : window.confirm(message);
      cb?.(ok);
    },
    showPopup(params, cb) {
      const txt = `${params.title ? params.title + "\n\n" : ""}${params.message}`;
      const ok = window.confirm(txt);
      cb?.(ok ? (params.buttons?.[0]?.id ?? "ok") : "cancel");
    },
    onEvent(type, handler) {
      let set = state.events.get(type);
      if (!set) { set = new Set(); state.events.set(type, set); }
      set.add(handler);
    },
    offEvent(type, handler) { state.events.get(type)?.delete(handler); },
    setHeaderColor(color) { this.headerColor = color; notify(); },
    setBackgroundColor(color) { this.backgroundColor = color; notify(); },
  };

  return {
    webApp,
    state,
    triggerMainClick: () => { HapticFeedback.impactOccurred("medium"); state.mainHandlers.forEach((h) => { try { h(); } catch { /* noop */ } }); },
    triggerBackClick: () => { state.backHandlers.forEach((h) => { try { h(); } catch { /* noop */ } }); },
    reset: () => {
      state.mainButtonVisible = false;
      state.mainButtonActive = true;
      state.mainButtonProgress = false;
      state.backButtonVisible = false;
      state.mainHandlers.clear();
      state.backHandlers.clear();
      state.events.clear();
      notify();
    },
  };
}

declare global {
  interface Window {
    Telegram?: { WebApp: TelegramWebApp };
  }
}
