/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowsIndexRouteImport } from './routes/flows.index'
import { Route as MFlowIdRouteImport } from './routes/m.$flowId'
import { Route as FlowsSlugRouteImport } from './routes/flows.$slug'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsIndexRoute = FlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => rootRouteImport,
} as any)
const MFlowIdRoute = MFlowIdRouteImport.update({
  id: '/m/$flowId',
  path: '/m/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsSlugRoute = FlowsSlugRouteImport.update({
  id: '/flows/$slug',
  path: '/flows/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/flows/$slug': typeof FlowsSlugRoute
  '/m/$flowId': typeof MFlowIdRoute
  '/flows/': typeof FlowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/flows/$slug': typeof FlowsSlugRoute
  '/m/$flowId': typeof MFlowIdRoute
  '/flows': typeof FlowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/flows/$slug': typeof FlowsSlugRoute
  '/m/$flowId': typeof MFlowIdRoute
  '/flows/': typeof FlowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/billing'
    | '/reset-password'
    | '/settings'
    | '/flows/$slug'
    | '/m/$flowId'
    | '/flows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/reset-password'
    | '/settings'
    | '/flows/$slug'
    | '/m/$flowId'
    | '/flows'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/billing'
    | '/reset-password'
    | '/settings'
    | '/flows/$slug'
    | '/m/$flowId'
    | '/flows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  FlowsSlugRoute: typeof FlowsSlugRoute
  MFlowIdRoute: typeof MFlowIdRoute
  FlowsIndexRoute: typeof FlowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/': {
      id: '/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof FlowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$flowId': {
      id: '/m/$flowId'
      path: '/m/$flowId'
      fullPath: '/m/$flowId'
      preLoaderRoute: typeof MFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$slug': {
      id: '/flows/$slug'
      path: '/flows/$slug'
      fullPath: '/flows/$slug'
      preLoaderRoute: typeof FlowsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  FlowsSlugRoute: FlowsSlugRoute,
  MFlowIdRoute: MFlowIdRoute,
  FlowsIndexRoute: FlowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
